defaults:
  theme: catppuccin-mocha
  terminal_font_size: 16

transition:
  # how long the transition should last.
  duration_millis: 750

  # how many frames should be rendered during the transition
  frames: 45

  # the animation to use
  animation:
    style: fade
